#!/usr/bin/env python3
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤
# 100 and 2 ≤ b ≤ 100?

terms = []
for a in range(2, 101):
    for b in range(2, 101):
        x = a**b
        if x not in terms:
            terms.append(x)

print(len(terms))
